export const GET_PRODUCTS = 'GET_PRODCUTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const ADMIN_GET_PRODUCTS = 'ADMIN_GET_PRODUCTS';
export const ADMIN_SELECT_PRODUCTS= 'ADMIN_SELECT_PRODUCTS';
export const ADMIN_SELECT_DELETED_PRODUCTS= 'ADMIN_SELECT_DELETED_PRODUCTS';
