export const GET_PRODUCTS = 'GET_PRODCUTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';