export const ADMIN_GET_PRODUCTS = "ADMIN_GET_PRODUCTS";
export const ADMIN_SELECT_PRODUCTS = "ADMIN_SELECT_PRODUCTS";
export const ADMIN_SELECT_DELETED_PRODUCTS = "ADMIN_SELECT_DELETED_PRODUCTS";
export const ADMIN_CLEAR_SELECT = "ADMIN_CLEAR_SELECT";
export const ADMIN_PRODUCT_SET_ACTIVE = "ADMIN_PRODUCT_SET_ACTIVE";
// product action names
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const FILTER_PRODUCTS_CATEGORY ='FILTER_PRODUCTS_CATEGORY'

// category action names
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// pagination action name
export const CURENT_PAGE = "CURENT_PAGE";

// search action name
export const SEARCH_STATE = "SEARCH_STATE";
